#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
setxkbmap -model pc104 -layout us,ru -variant qwerty -option grp:alt_space_toggle us,ru &
picom &
$HOME/.config/polybar/launch.sh
sleep 1
$HOME/.dotfiles/setdpi.sh &
$HOME/.screenlayout/layout.sh &
nitrogen --restore &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-1 1 2 3 4 5 6 7 8 9 10

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   10
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#d6dbe5"
bspc config active_border_color	              "#d6dbe5"
bspc config focused_border_color	      "#ffffff"
bspc config presel_feedback_color	      "#ffffff"
bspc config urgent_border_color 	      "#de352e"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a LibreWolf desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
